### ISSUE TITLE
点击Inspect/Debugger，位于Android模拟器上的程序crash.

### ISSUE THREAD

**Issue by snailrobert** [weexteam/weex-devtools-android#36]
11-10 16:12:49.993 1441-1459/today.firstweex E/AndroidRuntime: FATAL EXCEPTION: Thread-113
                                                               java.lang.NoClassDefFoundError: javax/annotation/Nonnull
                                                                   at java.lang.reflect.Method.isAnnotationPresent(Native Method)
                                                                   at java.lang.reflect.Method.isAnnotationPresent(Method.java:284)
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.isDevtoolsMethod(MethodDispatcher.java:136)
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:116)
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53)
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60)
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleRemoteRequest(DebugServerProxy.java:218)
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleRemoteMessage(DebugServerProxy.java:200)
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleMessage(DebugServerProxy.java:181)
                                                                   at com.taobao.weex.devtools.debug.DebugSocketClient.onMessage(DebugSocketClient.java:80)
                                                                   at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:53)
                                                                   at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:213)
                                                                   at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
                                                                   at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87)
                                                                   at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187)
                                                                   at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                   at java.lang.Thread.run(Thread.java:856)
                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.annotation.Nonnull" on path: /data/app/today.firstweex-1.apk
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                   at java.lang.reflect.Method.isAnnotationPresent(Native Method) 
                                                                   at java.lang.reflect.Method.isAnnotationPresent(Method.java:284) 
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.isDevtoolsMethod(MethodDispatcher.java:136) 
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.buildDispatchTable(MethodDispatcher.java:116) 
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.findMethodDispatcher(MethodDispatcher.java:53) 
                                                                   at com.taobao.weex.devtools.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:60) 
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleRemoteRequest(DebugServerProxy.java:218) 
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleRemoteMessage(DebugServerProxy.java:200) 
                                                                   at com.taobao.weex.devtools.debug.DebugServerProxy.handleMessage(DebugServerProxy.java:181) 
                                                                   at com.taobao.weex.devtools.debug.DebugSocketClient.onMessage(DebugSocketClient.java:80) 
                                                                   at com.squareup.okhttp.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:53) 
                                                                   at com.squareup.okhttp.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:213) 
                                                                   at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) 
                                                                   at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87) 
                                                                   at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187) 
                                                                   at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) 
                                                                   at java.lang.Thread.run(Thread.java:856)

**Comment by snailrobert** [comment]
weex dev tools为0.8, sdk为10号目前github上最新的。

**Comment by littleseven** [comment]
@snailrobert 如沟通，升级版本即可解决～
