### ISSUE TITLE
用okhttp 3.5 时直接启动崩溃

### ISSUE THREAD

**Issue by Neeeo** [weexteam/weex-devtools-android#49]
依赖
```gradle
compile 'com.squareup.okhttp3:okhttp:3.5.0'
```
崩溃 log
```java
FATAL EXCEPTION: DebugServerProxy
Process: com.boxhunt.galileo, PID: 25631
java.lang.IllegalArgumentException: okhttp3.WebSocketListener is not an interface
    at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:426)
    at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:741)
    at com.taobao.weex.devtools.debug.OkHttp35SocketClient.connect(OkHttp35SocketClient.java:127)
    at com.taobao.weex.devtools.debug.SocketClient$MessageHandler.handleMessage(SocketClient.java:103)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by misakuo** [comment]
okhttp 3.5.0做了接口修改，之前devtools里使用的动态代理机制不能work了，后面我会出一个兼容版本来解决这个问题

**Comment by Neeeo** [comment]
请问这个兼容版计划什么时候出？

**Comment by misakuo** [comment]
请使用`WeexInspector.overrideWebSocketClient()`来规避该问题
